# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequest do
  @moduledoc """
  Config of migrating one resource from automl.googleapis.com, datalabeling.googleapis.com and ml.googleapis.com to Vertex AI.

  ## Attributes

  *   `migrateAutomlDatasetConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateAutomlDatasetConfig.t`, *default:* `nil`) - Config for migrating Dataset in automl.googleapis.com to Vertex AI's Dataset.
  *   `migrateAutomlModelConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateAutomlModelConfig.t`, *default:* `nil`) - Config for migrating Model in automl.googleapis.com to Vertex AI's Model.
  *   `migrateDataLabelingDatasetConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateDataLabelingDatasetConfig.t`, *default:* `nil`) - Config for migrating Dataset in datalabeling.googleapis.com to Vertex AI's Dataset.
  *   `migrateMlEngineModelVersionConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateMlEngineModelVersionConfig.t`, *default:* `nil`) - Config for migrating Version in ml.googleapis.com to Vertex AI's Model.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :migrateAutomlDatasetConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateAutomlDatasetConfig.t()
            | nil,
          :migrateAutomlModelConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateAutomlModelConfig.t()
            | nil,
          :migrateDataLabelingDatasetConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateDataLabelingDatasetConfig.t()
            | nil,
          :migrateMlEngineModelVersionConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateMlEngineModelVersionConfig.t()
            | nil
        }

  field(:migrateAutomlDatasetConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateAutomlDatasetConfig
  )

  field(:migrateAutomlModelConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateAutomlModelConfig
  )

  field(:migrateDataLabelingDatasetConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateDataLabelingDatasetConfig
  )

  field(:migrateMlEngineModelVersionConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequestMigrateMlEngineModelVersionConfig
  )
end

defimpl Poison.Decoder,
  for: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequest do
  def decode(value, options) do
    GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequest.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1MigrateResourceRequest do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
