# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToAction do
  @moduledoc """
  Actions could take on this Publisher Model.

  ## Attributes

  *   `createApplication` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Create application using the PublisherModel.
  *   `deploy` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionDeploy.t`, *default:* `nil`) - Optional. Deploy the PublisherModel to Vertex Endpoint.
  *   `openEvaluationPipeline` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Open evaluation pipeline of the PublisherModel.
  *   `openFineTuningPipeline` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Open fine-tuning pipeline of the PublisherModel.
  *   `openGenerationAiStudio` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Open in Generation AI Studio.
  *   `openGenie` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Open Genie / Playground.
  *   `openNotebook` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Open notebook of the PublisherModel.
  *   `openPromptTuningPipeline` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Open prompt-tuning pipeline of the PublisherModel.
  *   `requestAccess` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t`, *default:* `nil`) - Optional. Request for access.
  *   `viewRestApi` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionViewRestApi.t`, *default:* `nil`) - Optional. To view Rest API docs.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :createApplication =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :deploy =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionDeploy.t()
            | nil,
          :openEvaluationPipeline =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :openFineTuningPipeline =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :openGenerationAiStudio =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :openGenie =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :openNotebook =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :openPromptTuningPipeline =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :requestAccess =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences.t()
            | nil,
          :viewRestApi =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionViewRestApi.t()
            | nil
        }

  field(:createApplication,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:deploy,
    as: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionDeploy
  )

  field(:openEvaluationPipeline,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:openFineTuningPipeline,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:openGenerationAiStudio,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:openGenie,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:openNotebook,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:openPromptTuningPipeline,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:requestAccess,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionRegionalResourceReferences
  )

  field(:viewRestApi,
    as: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToActionViewRestApi
  )
end

defimpl Poison.Decoder,
  for: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToAction do
  def decode(value, options) do
    GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToAction.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1PublisherModelCallToAction do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
