# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This file is auto generated by the elixir code generator program.
# Do not edit this file manually.

defmodule GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfig do
  @moduledoc """
  The objective configuration for model monitoring, including the information needed to detect anomalies for one particular model.

  ## Attributes

  *   `explanationConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigExplanationConfig.t`, *default:* `nil`) - The config for integrating with Vertex Explainable AI.
  *   `predictionDriftDetectionConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigPredictionDriftDetectionConfig.t`, *default:* `nil`) - The config for drift of prediction data.
  *   `trainingDataset` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigTrainingDataset.t`, *default:* `nil`) - Training dataset for models. This field has to be set only if TrainingPredictionSkewDetectionConfig is specified.
  *   `trainingPredictionSkewDetectionConfig` (*type:* `GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigTrainingPredictionSkewDetectionConfig.t`, *default:* `nil`) - The config for skew between training data and prediction data.
  """

  use GoogleApi.Gax.ModelBase

  @type t :: %__MODULE__{
          :explanationConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigExplanationConfig.t()
            | nil,
          :predictionDriftDetectionConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigPredictionDriftDetectionConfig.t()
            | nil,
          :trainingDataset =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigTrainingDataset.t()
            | nil,
          :trainingPredictionSkewDetectionConfig =>
            GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigTrainingPredictionSkewDetectionConfig.t()
            | nil
        }

  field(:explanationConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigExplanationConfig
  )

  field(:predictionDriftDetectionConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigPredictionDriftDetectionConfig
  )

  field(:trainingDataset,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigTrainingDataset
  )

  field(:trainingPredictionSkewDetectionConfig,
    as:
      GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfigTrainingPredictionSkewDetectionConfig
  )
end

defimpl Poison.Decoder,
  for: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfig do
  def decode(value, options) do
    GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfig.decode(
      value,
      options
    )
  end
end

defimpl Poison.Encoder,
  for: GoogleApi.AiPlatform.V1.Model.GoogleCloudAiplatformV1ModelMonitoringObjectiveConfig do
  def encode(value, options) do
    GoogleApi.Gax.ModelBase.encode(value, options)
  end
end
